language: node_js
node_js:
  - "stable"

sudo: false

notifications:
  email: false

cache:
  directories:
    - node_modules

branches:
  only:
    - master

install:
  - npm install

script:
  - npm run build

after_success:
  - npm run coverage